### ISSUE TITLE
co to nsearch ?

### ISSUE THREAD

**Issue by teleguest** [fnaxMC/nsearch#2]
to wyszukiwarka?

**Comment by fnaxMC** [comment]
tak. wyszukiwarka

**Comment by teleguest** [comment]
w czym ona będzie pisana w js czy pyhtonie ?

**Comment by fnaxMC** [comment]
w pythonie, ale ten projekt został porzucony przez to że biblioteka na której bazuje nie działa poprawnie

**Comment by teleguest** [comment]
ok
